baseURL: "https://kuang.dev/"
title: kuang.dev
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
pygmentsUseClasses: true

googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production
    title: kuang.dev
    description: "Personal website of Ning \"Alex\" Kuang"
    keywords: [Blog, Kuang Ning]
    author: Ning "Alex" Kuang
    # images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "Jan 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: true

    ShowReadingTime: false
    ShowShareButtons: false
    ShowPostNavLinks: true
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: true
    comments: true
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        # favicon: "<link / abs url>"
        # favicon16x16: "<link / abs url>"
        # favicon32x32: "<link / abs url>"
        # apple_touch_icon: "<link / abs url>"
        # safari_pinned_tab: "<link / abs url>"

    label:
        text: ' '
        icon: KUANG.svg
        iconDark: KUANG-dark.svg
        iconHeight: 20

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: ExampleSite
        subtitle: "This is subtitle"
        imageUrl: "<img location>"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "Yo."
        Content: Ning "Alex" Kuang here.

    socialIcons:
        - name: github
          url: "https://github.com/alexkuang0"
        - name: instagram
          url: "https://instagram.com/alexkuang0"
        - name: linkedin
          url: "https://linkedin.com/in/alexkuang0"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    editPost:
        URL: "https://github.com/alexkuang0/blog/blob/main/content"
        Text: "View on GitHub" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        includeMatches: true
        shouldSort: true
        location: 0
        distance: 100
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: tags
          name: tags
          url: /tags/
          weight: 20
        - identifier: archives
          name: archives
          url: /archives/
          weight: 30
        - identifier: search
          name: search
          url: /search/
          weight: 40
        - identifier: about
          name: about
          url: /about/
          weight: 50
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
markup:
    goldmark:
        renderer:
            unsafe: true
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

rssLimit: 10
taxonomies:
    tag: tags